site_name: 'Juji Documentation'
site_description: 'Tutorials, guides, and references for Juji chatbot creation platform'
site_url: 'https://www.juji.io'

#repo_name: 'juji-io/docs'
#repo_url: 'https://github.com/juji-io/docs'

copyright: 'Copyright &copy; 2019 Juji, Inc.'

google_analytics:
  - 'UA-108804735-1'
  - 'auto'

theme:
  logo: 'img/juji-logo.png'
  favicon: 'img/favicon.ico'
  name: 'material'
  custom_dir: 'theme/'
  palette:
    primary: 'white'
    accent: 'deep orange'

extra_css:
  - 'stylesheets/extra.css'

markdown_extensions:
  - def_list
  - admonition
  - footnotes
  - tables
  - meta
  - codehilite:
      guess_lang: false
      linenums: true
  - toc:
      toc_depth: '3'
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.striphtml:
      strip_attributes: ''

extra:
  social:
    - type: 'github'
      link: 'https://github.com/juji-io'
    - type: 'twitter'
      link: 'https://twitter.com/juji_io'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/company/juji-io/'

nav:
  - Get Started: index.md
  - Juji Studio:  juji-studio.md
  - Juji IDE: juji-ide.md
  - Juji API: api.md
  - FAQs: faq.md
  - Juji Forum: https://forum.juji.io
  - Sign up at Juji: https://juji.io/login
