site_name: 'Juji Documentation'
site_description: 'Tutorials, guides, and references for Juji AI chatbot creation platform'
site_url: 'https://juji.io/docs'

#repo_name: 'juji-io/docs'
#repo_url: 'https://github.com/juji-io/docs'

copyright: 'Copyright &copy; 2020 Juji, Inc.'

google_analytics:
  - 'UA-113933244-1'
  - 'auto'

theme:
  logo: 'img/juji-logo.png'
  favicon: 'img/favicon.ico'
  name: 'material'
  custom_dir: 'theme/'
  features:
    - tabs
    - instant

  palette:
    primary: 'white'
    accent: 'deep orange'

plugins:
  - search: 
      separator: '[\s\-\.]+'
      lang:
        - en

extra_css:
  - 'stylesheets/extra.css'

markdown_extensions:
  - def_list
  - admonition
  - footnotes
  - tables
  - meta
  - codehilite:
      guess_lang: false
      linenums: true
  - toc:
      toc_depth: '3'
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.striphtml:
      strip_attributes: ''

extra:
  social:
    - icon: 'fontawesome/brands/github'
      link: 'https://github.com/juji-io'
    - icon: 'fontawesome/brands/twitter'
      link: 'https://twitter.com/juji_io'
    - icon: 'fontawesome/brands/linkedin'
      link: 'https://www.linkedin.com/company/juji-io/'

nav:
  - Get Started: index.md
  - Juji Studio:  
    - Introduction: juji-studio.md
    - Chatbot Design: design.md
    - Chatbot Deployment: release.md
    - Chatbot Monitoring: reports.md
    - Design Best Practices: chatbot-design-tips.md
  - Juji IDE: 
    - Introduction: juji-ide.md
    - Concepts: concept.md
    - Language: reference.md
    - Built-in Dialog Library: topics.md
    - System Functions: function.md
    - User-defined Functions: udf.md
    - Script: script.md
  - Juji API: 
    - Introduction: api.md
    - Data Model: nouns.md
    - Chat API: chat.md
    - Data API: meta.md
  - Beginners' Guide to AI Chatbots:
    - Why AI Chatbots: why-ai-chatbots.md
    - Design Tips: chatbot-design-tips.md
    - Advanced: chatbot-design-tips-advanced.md
  - Juji Tutorials: tutorial.md  
  - Juji Forum: https://forum.juji.io
  - FAQs: faq.md
  - Trouble Shooting: trouble-shooting.md
  - Sign up on Juji: https://juji.ai/signup
  - Juji Homepage: https://juji.io
